# Project information
site_name: MinJoker's Notebook
site_url: https://minjoker.github.io
repo_name: MinJoker.github.io
repo_url: https://github.com/MinJoker/MinJoker.github.io
site_description: MinJoker 的笔记本
site_author: MinJoker
copyright: Copyright <span style="font-family:Arial;">&copy;</span> 2023 <a href="https://github.com/MinJoker" target="_blank">MinJoker</a>

# Build directories
theme:
  name: material
  icon:
    logo: material/drama-masks
  favicon: assets/icons/drama-masks-white.svg
  font: false
  features: 
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - header.autohide
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
#  - javascripts/mathjax.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MinJoker
    - icon: fontawesome/brands/google
      link: mailto:jokermin551008@gmail.com

# Formatting options
markdown_extensions:
  #Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 4
  #Python Markdown Extensions
#  - pymdownx.arithmatex:
#      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - statistics
#      page_check_metadata: <metadata>  # strict indentation ( tab )
  - git-revision-date-localized:
      type: iso_datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
      

# Documentation layout
nav:
  - Home:
    - index.md

  - Computer Science:
    - cs/index.md
    - 数据结构与算法:
      - cs/algorithms/index.md
      - cs/algorithms/lec1.md

  - Mathematics:
    - math/index.md

  - BCI:
    - bci/index.md
    - 脑机接口导论:
      - bci/bciai/index.md
      - bci/bciai/ch3.md
      - bci/bciai/ch4.md
      - bci/bciai/ch5.md

  - Photography:
    - photo/index.md

  - Others:
    - others/index.md
